spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://192.168.0.100:5432/news
    username: student
    password: student
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE